### ISSUE TITLE
关于第二阶段的合作

### ISSUE THREAD

**Issue by theJian** [DieInGame/ife-task-2#1]
承接上文:　https://github.com/DieInGame/ife-task-1/issues/1
- 分支

上一阶段中 task 7 发现合作方面的一些问题, 由于分支是以人划分的, task 7 中 zhe13 和 Fiona 的实现都有各自的优点, 但是开始时两位基本是各写各的, 这两份代码基本是没法合并的, 所以我的想法是这次是否尝试以任务划分分支, 比如我选了任务8, 那么我就从 master 分出一个 分支 task-08:
1. 通过查看分支, 所有人都能一目了然哪些 task 正在执行.
2. 由分支的拥有人主导这个 task, 贡献或者修复bug提pr给该分支, pr 由分支的拥有者自行处理.
3. 分支的拥有人自己把控进度, 确认完成后提 pr 给 master 进行 review.

**Comment by zhe13** [comment]
小师妹还帮我改CSS＝－＝另一个师哥已经彻底滑水消失了。
我们的队名真好。A  。

**Comment by Fiooona** [comment]
同意。。%>_<%，看完别人写的感觉不难，自己写又写不出来，好忧伤。
