### ISSUE TITLE
Task-17

### ISSUE THREAD

**Issue by zhe13** [DieInGame/ife-task-2#20]
数据归类我已经做好了，最后就是可视化。
数据类型注释里标注好了，或者直接console中查看chartData。
在html中做了一个dom柱形图的示例。
render（）函数没写，今天没功夫写了，有人愿意接锅嘛。
@Fiooona 美丽动人的小天使。
@theJian 帅气的滑水大王

**Comment by zhe13** [comment]
@pollyu522 一直隐身看代码的小学妹

**Comment by Fiooona** [comment]
来来来，放着我来：p

**Comment by theJian** [comment]
这锅宝宝不接

**Comment by theJian** [comment]
话说还有两位童鞋是退出了吗

**Comment by zhe13** [comment]
不知道啊＝－＝我去问问小学妹我估计是不会用pr和git team。就当它们消失了吧

**Comment by theJian** [comment]
不会可以学啊， 可以查啊， 可以问啊

**Comment by Fiooona** [comment]
这个render（）函数 写的我好凌乱，你们不要着急，我再凌乱一会：（

**Comment by zhe13** [comment]
莫慌，弄不好的话我上完课晚上回来接手
