### ISSUE TITLE
距离 deadline 还有10天

### ISSUE THREAD

**Issue by theJian** [DieInGame/ife-task-2#21]
**must finished**
- 飞船一系列 task
- 指令方块一系列 task

**Comment by zhe13** [comment]
好的 。飞船周三前所有搞定

**Comment by theJian** [comment]
现在飞船差两个 task，
指令方块差两个 task，
接下来差不多 2 - 3 天 要完成并 review 一个 task， 时间很紧

**Comment by zhe13** [comment]
方块我看着办

**Comment by Fiooona** [comment]
介于我的水平比较菜、我觉得我还是继续做简单的题目吧：（
