### ISSUE TITLE
分支fiooona-patch-1

### ISSUE THREAD

**Issue by Fiooona** [DieInGame/ife-task-2#23]
Task 35 里，main.js修改了 function sbumitcommand ，有BUG ，只有go 这个指令能用，其他的指令都失灵了：（
公司里没有人帮我看代码，他们都是土木男，没有程序猿，(https://github.com/DieInGame/ife-task-2/blob/Fiooona-patch-1/35/js/main.js)

**Comment by theJian** [comment]
注意你 return 的位置，38行那里，外层的for循环并不会执行完，只执行了一次就被return了

**Comment by Fiooona** [comment]
不会了 这个task 我就只能做到这了、、好无力
