### ISSUE TITLE
Task 26 Testing & Enhancement

### ISSUE THREAD

**Issue by theJian** [DieInGame/ife-task-2#5]
Task 26 做完了， 开放PR， 大家来帮忙找bug和优化吧

**Comment by Fiooona** [comment]
不懂、、我下载下来的有错误，

**Comment by theJian** [comment]
....

**Comment by theJian** [comment]
什么错误

**Comment by theJian** [comment]
你用什么浏览器, 代码用了 canvas 和 es6 特性, 是不是不支持

**Comment by Fiooona** [comment]
chorme啊，
：Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
不支持严格模式？
你用的什么浏览器

**Comment by theJian** [comment]
不好意思, Spaceship.js 里的 "use strict" 拼错了

**Comment by theJian** [comment]
改好了, 你再试试

**Comment by Fiooona** [comment]
Uncaught SyntaxError: Unexpected token =                                   Spaceship.js:4
Uncaught ReferenceError: SpaceShip is not defined                    main.js:7

**Comment by theJian** [comment]
我在 chromium Version 49.0.2623.108 (64-bit) Linux 和 chrome Version 49.0.2623.110m Windows 10 上都测试通过了, 你提个新的 Bug Issue 吧, 附上具体的版本信息

**Comment by Fiooona** [comment]
把浏览器更新了，没问题。找不到bug 只是刚能懂，让 @satansk @zhe13 来看看吧~

**Comment by zhe13** [comment]
来了。我先看一百个单词，稍等
